'use client';

import { motion } from 'framer-motion';
import { ShieldAlert, CheckCircle, ExternalLink } from 'lucide-react';

export function Audits() {
  // Simulated audit data for the "Better UX" requirement
  const audits = [
    { id: 1, name: "Project-Alpha-v1", status: "passed", date: "2024-10-15", auditor: "CertiK" },
    { id: 2, name: "Token-Swap-Module", status: "pending", date: "2024-12-20", auditor: "CedraSecurity" },
    { id: 3, name: "Current-Forge-Session", status: "unsubmitted", date: "Today", auditor: "-" },
  ];

  return (
    <div className="h-full w-full overflow-y-auto p-8 max-w-5xl mx-auto">
         <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-8"
        >
            <div className="border-b border-border pb-6 flex justify-between items-end">
                <div>
                    <h1 className="text-3xl font-bold text-white flex items-center gap-3">
                        <ShieldAlert className="text-secondary h-8 w-8" />
                        Audit Dashboard
                    </h1>
                    <p className="text-gray-400 mt-2">
                        Track the security status of your forged smart contracts.
                    </p>
                </div>
                <button className="px-4 py-2 bg-primary/10 text-primary border border-primary/50 rounded-md text-sm hover:bg-primary/20 transition-colors">
                    Request New Audit
                </button>
            </div>

            <div className="grid gap-4">
                {audits.map((audit) => (
                    <div key={audit.id} className="bg-surface-highlight/30 border border-border rounded-lg p-6 flex items-center justify-between hover:border-primary/50 transition-colors">
                        <div className="flex items-center gap-4">
                            <div className={`w-3 h-3 rounded-full ${
                                audit.status === 'passed' ? 'bg-green-500 shadow-[0_0_10px_rgba(34,197,94,0.5)]' : 
                                audit.status === 'pending' ? 'bg-yellow-500 shadow-[0_0_10px_rgba(234,179,8,0.5)]' : 
                                'bg-red-500 shadow-[0_0_10px_rgba(239,68,68,0.5)]'
                            }`}></div>
                            <div>
                                <h3 className="font-mono text-lg font-bold text-white">{audit.name}</h3>
                                <p className="text-xs text-gray-500">Last updated: {audit.date}</p>
                            </div>
                        </div>

                        <div className="flex items-center gap-8 text-sm">
                            <div className="text-right">
                                <p className="text-gray-500 text-xs uppercase tracking-wider">Auditor</p>
                                <p className="text-gray-300">{audit.auditor}</p>
                            </div>
                            <div className="text-right w-32">
                                <p className="text-gray-500 text-xs uppercase tracking-wider">Status</p>
                                <div className={`font-bold uppercase ${
                                    audit.status === 'passed' ? 'text-green-400' : 
                                    audit.status === 'pending' ? 'text-yellow-400' : 
                                    'text-red-400'
                                }`}>
                                    {audit.status}
                                </div>
                            </div>
                            <button className="p-2 hover:bg-white/5 rounded-full text-gray-400 hover:text-white">
                                <ExternalLink className="w-4 h-4" />
                            </button>
                        </div>
                    </div>
                ))}
            </div>

            <div className="bg-secondary/5 border border-secondary/20 rounded-lg p-4 mt-8">
                 <h4 className="text-secondary font-bold flex items-center gap-2 mb-2">
                    <ShieldAlert className="w-4 h-4" />
                    Security Notice
                 </h4>
                 <p className="text-gray-400 text-sm">
                    All code generated by Creatorium is experimental. 
                    <span className="text-white font-bold ml-1">Do not deploy to Mainnet without a professional audit.</span>
                 </p>
            </div>
        </motion.div>
    </div>
  );
}
